#server:
#  port: 8101
#spring:
#  application:
#    name: basic-payment-service
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      url: jdbc:mysql://127.0.0.1:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=true
#      username: root
#      password: 123456
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8201/eureka
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.seenda.payment.entity.Application
spring:
  profiles:
    active: dev
    #active: sit