server:
  port: 8002
spring:
  application:
    name: business-api-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
management:
  endpoints:
    web:
      exposure:
        include: '*'
