server:
  port: 8105
spring:
  application:
    name: basic-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  redis:
    database: 0
    host: 192.168.1.154
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 6000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seenda.basic.user.entity
management:
  endpoints:
    web:
      exposure:
        include: '*'