server:
  port: 8201
spring:
  application:
    name: component-eureka-service
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 45
    lease-renewal-interval-in-seconds: 30
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registry-fetch-interval-seconds: 5

